  - name: Print IP Address
    shell:  echo Eslam Samy Hosney
    register: print_result

  #show the output on the user/us Cli
  - name: print message
    debug:
      msg: "{{ print_result.stdout_lines }}"

  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: yes
    apt:
      autoremove: yes
      
  - name: "Install Kubectl"
    shell: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl  /usr/local/bin/
        kubectl version --client -o json

  - name: "Install Docker"
    shell: |
        #sudo apt install docker.io
        #sudo apt-get install -y docker.io
        sudo apt-get update && sudo apt-get install docker.io -y
    
  - name: "Install Minikube"
    shell: |
        wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube-linux-amd64
        sudo mv minikube-linux-amd64 /usr/local/bin/minikube
        minikube version
    register: out
        
  - debug: var=out.stdout_lines
  
  - name: "Start Minikube"
    shell: |
        #sudo usermod -aG docker $USER && newgrp docker
        #sudo -i
        minikube start --driver=docker
        #minikube start
        #--driver=docker
    register: out
  
  - debug: var=out.stdout_lines


        
        
  - name: "Kubernetes Run"
    shell: |
        docker pull eslamhosney/udacity_devops_engineer_capstone:latest      
        kubectl run udacity-devops-engineer-capstone-deploy --image=eslamhosney/udacity_devops_engineer_capstone --port=80 --labels app=udacity-devops-engineer-capstone-deploy

  - name: "wait 60 seconds for target connection to become reachable/usable."
    wait_for_connection:
      timeout: 60
      
  - name: "Kubernetes Port forwward"
    shell: |
        kubectl port-forward udacity-devops-engineer-capstone-deploy 8000:80 --address='0.0.0.0'


