# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  print_pipeline_id:
    description: "A very simple command to print workflow ID"
    parameters:
      id:
        type: string
    steps:
      - run:
          name: "print workflow ID"
          command: echo <<parameters.id>>
      

jobs:
  print-workflow-id:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - print_pipeline_id:
          id: <<pipeline.id>>
          
  lint-Python:
    docker:
      # specify the version you desire here
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # run lints!
      - run:
          name: run python lint
          command: |
            . venv/bin/activate
            pylint --disable=R,C,W1203,W1202 app.py
            
  lint-Dockerfile:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            #install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
        
      # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            hadolint Dockerfile

#################################################

  test-app:
    docker:
      # specify the version you desire here
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # run lints!
      - run:
          name: run app.py
          command: |
            . venv/bin/activate
            pytest test_api.py

#################################################

  security-app:
    docker:
      # specify the version you desire here
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # run lints!
      - run:
          name: run app.py
          command: |
            . venv/bin/activate
            bandit app.py

workflows:
  print-workflow-workflow:
    jobs:
      - print-workflow-id
      - lint-Python:
            requires: [print-workflow-id]
            filters:
              branches:
                only: [main]
      - lint-Dockerfile:
            requires: [print-workflow-id]
            filters:
              branches:
                only: [main]
      - test-app:
            #requires: [lint-Python, lint-Dockerfile]
            filters:
              branches:
                only: [main]
      - security-app:
            #requires: [lint-Python, lint-Dockerfile]
            filters:
              branches:
                only: [main]  